ANNOTATION:
  DATASET_NAME: 'MECCANO'

MECCANO:
  # Path to the directory containing the videos
  VIDEOS_DIR: '/home/retrocausal-train/Desktop/Procedural-Learning/EGOPROCEL-INTERNAL/videos/MECCANO'
  # VIDEOS_DIR: '/media/retrocausal-train/Extreme SSD1/Egoprocel/videos/MECCANO'
  # Path to the directory for saving the frames
  FRAMES_DIR: './MECCANO-frames'
  # Path to the directory contatining the annotations
  ANNS_DIR: '/home/retrocausal-train/Desktop/Procedural-Learning/EGOPROCEL-INTERNAL/annotations/MECCANO'
  # ANNS_DIR: '/media/retrocausal-train/Extreme SSD1/Egoprocel/annotations/MECCANO'

DATA_LOADER:
# Set with the dataset you are currently using
  NAME: 'MECCANO'
# Number of data loader workers per training process CHANGED FROM 4 TO 0
  NUM_WORKERS: 0
# CHANGED FROM TRUE TO FALSE
  SHUFFLE: False

MISC:
  # Print detailed output of steps taking place
  VERBOSE: True

LOG:
  # Path to the directory to save all the outputs from an experiment (including
  # visualisations, logs, results, etc.)
  DIR: ./logs/exp1

TCC:
  # Path to the directory containing videos for training
  DATA_PATH: '/home/retrocausal-train/Desktop/Procedural-Learning/EGOPROCEL-INTERNAL/videos/MECCANO'
  # DATA_PATH: '/media/retrocausal-train/Extreme SSD1/Egoprocel/videos/MECCANO'

LAV:
  # The final loss combines both TCC and C-IDM (referred to as TC3I loss)
  # If true, use Contrastive-IDM loss for training along with TCC
  USE_CIDM: True
  # (Regularization parameter) Contribution percent of temporal regularisation when adding with TCC
  #IT SHOULD BE CONTRIB_PERCENT: 1.0 acc to paper not 0.1
  CONTRIB_PERCENT: 1.0

  # Window size, Default to 10 seconds (30 fps) for CMU Kitchens
  SIGMA: 300.0
  # Margin
  LAMBDA: 2.0
